### PR TITLE
plots+path+debugger

### PR DESCRIPTION
**Pull request by DfAC**
Changes to Matlab code, including:
* full screen plots
* auto add/remove folder to the path
* added debugger and timing commands

### CODE REVIEW

**Comment by DfAC** [comment]
Agreement submitted

**Comment by edwardchen123** [comment]
Could someone provide the phones brand and type which support this raw measurements access. I thought maybe some phone which even if support Android N could not support raw data access, since the chip sets in the smartphone differs.

**Comment by DfAC** [comment]
Model | OS | Pseudorange and Pseudorange Rate | Nav data | Accumulated Delta Range or Carrier | HW clock | Raw | Meas. | Notes
--- | --- |:---:|:---:|:---:|:---:|--- | --- |---
Nexus 9 (Non cellular version) | N  | (7.1) | yes | yes | yes | yes | GPS+ GLONASS | Raw measurements are always available. No duty cycling. | Works only on the no-Cellular version of Nexus 9.
Nexus 5x | N | yes | no | no | no | Only GPS | Raw measurements are provided only when a fix available
Nexus 6P | N | yes | no | no | no | Only GPS | Raw measurements are provided only when a fix available
Pixel | N | yes | no | no  | yes | Only GPS | Raw measurements are always available
Pixel XL | N | yes | no | no | yes | Only GPS | Raw measurements are always available

**Comment by DfAC** [comment]
updated the code and created new pull request

**Comment by ZiglioNZ** [comment]
@DfAC Thank you for your table, it's awesome, and should be part of the official documentation somewhere. I'm interesting in other Nougat phones such as the Moto G4

@gpsFrank it'd be awesome if Google could offer a Rinex service (or equivalent), with at least hourly updates. I'm struggling to access the usual sites via FTP, it's not supported on Google App Engine for example. We're now left with "http" only which is faster but not supported by many sites. I'm also looking at other services such as SUPL but documentation/code is sparse. It's for AGPS, I know your book by heart... :-)

**Comment by barbeau** [comment]
More in this GPS World article too:
http://gpsworld.com/innovation-precise-positioning-using-raw-gps-measurements-from-android-smartphones/

**Comment by DfAC** [comment]
@ZiglioNZ [IGN offers hourly service](cddis.gsfc.nasa.gov/pub/gps/data/) you can write a script to grab data. On google apps you can use flask for example to emulate FTP functionality.
	ssssdddf.yyt
   |   |  | | |
   |   |  | | +--  t:  file type:
   |   |  | |          O: Observation file
   |   |  | |          N: GPS Navigation file
   |   |  | |          M: Meteorological data file
   |   |  | |          G: GLONASS Navigation file
   |   |  | |          L: Future Galileo Navigation file
   |   |  | |          H: Geostationary GPS payload nav mess file
   |   |  | |          B: Geo SBAS broadcast data file
   |   |  | |                        (separate documentation)
   |   |  | |          C: Clock file (separate documentation)
   |   |  | |          S: Summary file (used e.g., by IGS, not a standard!)
   |   |  | |
   |   |  | +---  yy:  two-digit year
   |   |  |
   |   |  +-----   f:  file sequence number/character within day
   |   |               daily file: f = 0
   |   |               hourly files:
   |   |               f = a:  1st hour 00h-01h; f = b: 2nd hour 01h-02h; ...
   |   |               f = x: 24th hour 23h-24h
   |   |
   |   +-------  ddd:  day of the year of first record
   |
   +----------- ssss:  4-character station name designator

**Comment by ZiglioNZ** [comment]
Thanks @DfAC 

unfortunately I don't think Flask would help. The problem we have is that Google App Engine standard blocks a range of outgoing/incoming IP ports, including the ones needed for FTP. [It used to work](https://groups.google.com/d/msg/google-appengine/mVVDE4wECbY/7iL6FjnhCQAJ) but no longer.
So that leaves us with the http option that luckily is supported by [Garner](http://garner.ucsd.edu/) but only for daily Rinexes.
I'm not aware of any other service that provides Rinex data via http. If anybody is aware, please let me know, including commercial options.
Ideally we would like to use immediately available ephemeris data.

**Comment by ZiglioUK** [comment]
@DfAC I've finally found what I needed: the IGS UltraRapid solutions in SP3 format, also available via http (App Engine-friendly): https://igscb.jpl.nasa.gov/components/prods_cb.html
I know it shouldn't come as a surprise for veterans of this industry

**Comment by DfAC** [comment]
That's useful knowledge - I tend to use FTP protocol provided by the other
IGS service. Thank you for this update

**Pull request closed without merging**
